/**
 * Verifiable US city/state data for the persona editor's CITY typeahead.
 * Curated: major metros, state capitals, and notable real-estate markets.
 * Not exhaustive — smaller towns can still be typed free-form (shown as
 * unverified, never blocked).
 */

export const US_STATES: string[] = [
  "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN",
  "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ",
  "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA",
  "WI", "WV", "WY",
];

export interface USCity { c: string; s: string }

export const US_CITIES: USCity[] = [
  { c: "New York", s: "NY" }, { c: "Los Angeles", s: "CA" }, { c: "Chicago", s: "IL" },
  { c: "Houston", s: "TX" }, { c: "Phoenix", s: "AZ" }, { c: "Philadelphia", s: "PA" },
  { c: "San Antonio", s: "TX" }, { c: "San Diego", s: "CA" }, { c: "Dallas", s: "TX" },
  { c: "Austin", s: "TX" }, { c: "Jacksonville", s: "FL" }, { c: "Fort Worth", s: "TX" },
  { c: "Columbus", s: "OH" }, { c: "Charlotte", s: "NC" }, { c: "San Francisco", s: "CA" },
  { c: "Indianapolis", s: "IN" }, { c: "Seattle", s: "WA" }, { c: "Denver", s: "CO" },
  { c: "Washington", s: "DC" }, { c: "Boston", s: "MA" }, { c: "El Paso", s: "TX" },
  { c: "Nashville", s: "TN" }, { c: "Detroit", s: "MI" }, { c: "Oklahoma City", s: "OK" },
  { c: "Portland", s: "OR" }, { c: "Las Vegas", s: "NV" }, { c: "Memphis", s: "TN" },
  { c: "Louisville", s: "KY" }, { c: "Baltimore", s: "MD" }, { c: "Milwaukee", s: "WI" },
  { c: "Albuquerque", s: "NM" }, { c: "Tucson", s: "AZ" }, { c: "Fresno", s: "CA" },
  { c: "Sacramento", s: "CA" }, { c: "Mesa", s: "AZ" }, { c: "Kansas City", s: "MO" },
  { c: "Atlanta", s: "GA" }, { c: "Omaha", s: "NE" }, { c: "Colorado Springs", s: "CO" },
  { c: "Raleigh", s: "NC" }, { c: "Miami", s: "FL" }, { c: "Long Beach", s: "CA" },
  { c: "Virginia Beach", s: "VA" }, { c: "Oakland", s: "CA" }, { c: "Minneapolis", s: "MN" },
  { c: "Tulsa", s: "OK" }, { c: "Tampa", s: "FL" }, { c: "Arlington", s: "TX" },
  { c: "New Orleans", s: "LA" }, { c: "Wichita", s: "KS" }, { c: "Cleveland", s: "OH" },
  { c: "Bakersfield", s: "CA" }, { c: "Aurora", s: "CO" }, { c: "Anaheim", s: "CA" },
  { c: "Honolulu", s: "HI" }, { c: "Santa Ana", s: "CA" }, { c: "Riverside", s: "CA" },
  { c: "Corpus Christi", s: "TX" }, { c: "Lexington", s: "KY" }, { c: "Stockton", s: "CA" },
  { c: "Henderson", s: "NV" }, { c: "Saint Paul", s: "MN" }, { c: "St. Louis", s: "MO" },
  { c: "Cincinnati", s: "OH" }, { c: "Pittsburgh", s: "PA" }, { c: "Greensboro", s: "NC" },
  { c: "Anchorage", s: "AK" }, { c: "Plano", s: "TX" }, { c: "Lincoln", s: "NE" },
  { c: "Orlando", s: "FL" }, { c: "Irvine", s: "CA" }, { c: "Newark", s: "NJ" },
  { c: "Durham", s: "NC" }, { c: "Chula Vista", s: "CA" }, { c: "Toledo", s: "OH" },
  { c: "Fort Wayne", s: "IN" }, { c: "St. Petersburg", s: "FL" }, { c: "Laredo", s: "TX" },
  { c: "Jersey City", s: "NJ" }, { c: "Chandler", s: "AZ" }, { c: "Madison", s: "WI" },
  { c: "Lubbock", s: "TX" }, { c: "Scottsdale", s: "AZ" }, { c: "Reno", s: "NV" },
  { c: "Buffalo", s: "NY" }, { c: "Gilbert", s: "AZ" }, { c: "Glendale", s: "AZ" },
  { c: "North Las Vegas", s: "NV" }, { c: "Winston-Salem", s: "NC" }, { c: "Chesapeake", s: "VA" },
  { c: "Norfolk", s: "VA" }, { c: "Fremont", s: "CA" }, { c: "Garland", s: "TX" },
  { c: "Irving", s: "TX" }, { c: "Hialeah", s: "FL" }, { c: "Richmond", s: "VA" },
  { c: "Boise", s: "ID" }, { c: "Spokane", s: "WA" }, { c: "Baton Rouge", s: "LA" },
  { c: "Tacoma", s: "WA" }, { c: "San Bernardino", s: "CA" }, { c: "Modesto", s: "CA" },
  { c: "Fontana", s: "CA" }, { c: "Des Moines", s: "IA" }, { c: "Moreno Valley", s: "CA" },
  { c: "Santa Clarita", s: "CA" }, { c: "Fayetteville", s: "NC" }, { c: "Birmingham", s: "AL" },
  { c: "Oxnard", s: "CA" }, { c: "Rochester", s: "NY" }, { c: "Port St. Lucie", s: "FL" },
  { c: "Grand Rapids", s: "MI" }, { c: "Huntsville", s: "AL" }, { c: "Salt Lake City", s: "UT" },
  { c: "Frisco", s: "TX" }, { c: "Yonkers", s: "NY" }, { c: "Amarillo", s: "TX" },
  { c: "Glendale", s: "CA" }, { c: "Huntington Beach", s: "CA" }, { c: "McKinney", s: "TX" },
  { c: "Montgomery", s: "AL" }, { c: "Augusta", s: "GA" }, { c: "Akron", s: "OH" },
  { c: "Little Rock", s: "AR" }, { c: "Tempe", s: "AZ" }, { c: "Columbus", s: "GA" },
  { c: "Overland Park", s: "KS" }, { c: "Grand Prairie", s: "TX" }, { c: "Tallahassee", s: "FL" },
  { c: "Cape Coral", s: "FL" }, { c: "Mobile", s: "AL" }, { c: "Knoxville", s: "TN" },
  { c: "Shreveport", s: "LA" }, { c: "Worcester", s: "MA" }, { c: "Ontario", s: "CA" },
  { c: "Vancouver", s: "WA" }, { c: "Sioux Falls", s: "SD" }, { c: "Chattanooga", s: "TN" },
  { c: "Brownsville", s: "TX" }, { c: "Fort Lauderdale", s: "FL" }, { c: "Providence", s: "RI" },
  { c: "Newport News", s: "VA" }, { c: "Rancho Cucamonga", s: "CA" }, { c: "Santa Rosa", s: "CA" },
  { c: "Peoria", s: "AZ" }, { c: "Oceanside", s: "CA" }, { c: "Elk Grove", s: "CA" },
  { c: "Salem", s: "OR" }, { c: "Pembroke Pines", s: "FL" }, { c: "Eugene", s: "OR" },
  { c: "Garden Grove", s: "CA" }, { c: "Cary", s: "NC" }, { c: "Fort Collins", s: "CO" },
  { c: "Corona", s: "CA" }, { c: "Springfield", s: "MO" }, { c: "Jackson", s: "MS" },
  { c: "Alexandria", s: "VA" }, { c: "Hayward", s: "CA" }, { c: "Clarksville", s: "TN" },
  { c: "Lakewood", s: "CO" }, { c: "Lancaster", s: "CA" }, { c: "Salinas", s: "CA" },
  { c: "Palmdale", s: "CA" }, { c: "Hollywood", s: "FL" }, { c: "Macon", s: "GA" },
  { c: "Kansas City", s: "KS" }, { c: "Sunnyvale", s: "CA" }, { c: "Pomona", s: "CA" },
  { c: "Escondido", s: "CA" }, { c: "Killeen", s: "TX" }, { c: "Naperville", s: "IL" },
  { c: "Joliet", s: "IL" }, { c: "Bellevue", s: "WA" }, { c: "Rockford", s: "IL" },
  { c: "Savannah", s: "GA" }, { c: "Paterson", s: "NJ" }, { c: "Torrance", s: "CA" },
  { c: "Bridgeport", s: "CT" }, { c: "McAllen", s: "TX" }, { c: "Mesquite", s: "TX" },
  { c: "Syracuse", s: "NY" }, { c: "Midland", s: "TX" }, { c: "Pasadena", s: "TX" },
  { c: "Murfreesboro", s: "TN" }, { c: "Miramar", s: "FL" }, { c: "Dayton", s: "OH" },
  { c: "Fullerton", s: "CA" }, { c: "Olathe", s: "KS" }, { c: "Orange", s: "CA" },
  { c: "Thornton", s: "CO" }, { c: "Roseville", s: "CA" }, { c: "Denton", s: "TX" },
  { c: "Waco", s: "TX" }, { c: "Surprise", s: "AZ" }, { c: "Carrollton", s: "TX" },
  { c: "West Valley City", s: "UT" }, { c: "Charleston", s: "SC" }, { c: "Warren", s: "MI" },
  { c: "Hampton", s: "VA" }, { c: "Gainesville", s: "FL" }, { c: "Visalia", s: "CA" },
  { c: "Coral Springs", s: "FL" }, { c: "Columbia", s: "SC" }, { c: "Cedar Rapids", s: "IA" },
  { c: "Sterling Heights", s: "MI" }, { c: "New Haven", s: "CT" }, { c: "Stamford", s: "CT" },
  { c: "Concord", s: "CA" }, { c: "Kent", s: "WA" }, { c: "Santa Clara", s: "CA" },
  { c: "Elizabeth", s: "NJ" }, { c: "Round Rock", s: "TX" }, { c: "Thousand Oaks", s: "CA" },
  { c: "Lafayette", s: "LA" }, { c: "Athens", s: "GA" }, { c: "Topeka", s: "KS" },
  { c: "Simi Valley", s: "CA" }, { c: "Fargo", s: "ND" }, { c: "Norman", s: "OK" },
  { c: "Columbia", s: "MO" }, { c: "Abilene", s: "TX" }, { c: "Wilmington", s: "NC" },
  { c: "Hartford", s: "CT" }, { c: "Victorville", s: "CA" }, { c: "Pearland", s: "TX" },
  { c: "Vallejo", s: "CA" }, { c: "Ann Arbor", s: "MI" }, { c: "Berkeley", s: "CA" },
  { c: "Allentown", s: "PA" }, { c: "Richardson", s: "TX" }, { c: "Odessa", s: "TX" },
  { c: "Arvada", s: "CO" }, { c: "Cambridge", s: "MA" }, { c: "Sugar Land", s: "TX" },
  { c: "Beaumont", s: "TX" }, { c: "Lansing", s: "MI" }, { c: "Evansville", s: "IN" },
  { c: "Rochester", s: "MN" }, { c: "Independence", s: "MO" }, { c: "Fairfield", s: "CA" },
  { c: "Provo", s: "UT" }, { c: "Clearwater", s: "FL" }, { c: "College Station", s: "TX" },
  { c: "West Jordan", s: "UT" }, { c: "Carlsbad", s: "CA" }, { c: "El Monte", s: "CA" },
  { c: "Murrieta", s: "CA" }, { c: "Temecula", s: "CA" }, { c: "Springfield", s: "MA" },
  { c: "Palm Bay", s: "FL" }, { c: "Costa Mesa", s: "CA" }, { c: "Westminster", s: "CO" },
  { c: "North Charleston", s: "SC" }, { c: "Miami Gardens", s: "FL" }, { c: "Manchester", s: "NH" },
  { c: "High Point", s: "NC" }, { c: "Downey", s: "CA" }, { c: "Clovis", s: "CA" },
  { c: "Pompano Beach", s: "FL" }, { c: "Pueblo", s: "CO" }, { c: "Elgin", s: "IL" },
  { c: "Lowell", s: "MA" }, { c: "Antioch", s: "CA" }, { c: "West Palm Beach", s: "FL" },
  { c: "Everett", s: "WA" }, { c: "Ventura", s: "CA" }, { c: "Centennial", s: "CO" },
  { c: "Lakeland", s: "FL" }, { c: "Gresham", s: "OR" }, { c: "Richmond", s: "CA" },
  { c: "Billings", s: "MT" }, { c: "Inglewood", s: "CA" }, { c: "Broken Arrow", s: "OK" },
  { c: "Sandy Springs", s: "GA" }, { c: "Jurupa Valley", s: "CA" }, { c: "Hillsboro", s: "OR" },
  { c: "Waterbury", s: "CT" }, { c: "Santa Maria", s: "CA" }, { c: "Boulder", s: "CO" },
  { c: "Greeley", s: "CO" }, { c: "Daly City", s: "CA" }, { c: "Meridian", s: "ID" },
  { c: "Lewisville", s: "TX" }, { c: "Davie", s: "FL" }, { c: "West Covina", s: "CA" },
  { c: "League City", s: "TX" }, { c: "Tyler", s: "TX" }, { c: "Norwalk", s: "CA" },
  { c: "San Mateo", s: "CA" }, { c: "Green Bay", s: "WI" }, { c: "Wichita Falls", s: "TX" },
  { c: "Sparks", s: "NV" }, { c: "Lakewood", s: "NJ" }, { c: "Burbank", s: "CA" },
  { c: "Rialto", s: "CA" }, { c: "Allen", s: "TX" }, { c: "El Cajon", s: "CA" },
  { c: "Las Cruces", s: "NM" }, { c: "Renton", s: "WA" }, { c: "Davenport", s: "IA" },
  { c: "South Bend", s: "IN" }, { c: "Vista", s: "CA" }, { c: "Tuscaloosa", s: "AL" },
  { c: "Clinton", s: "MI" }, { c: "Edison", s: "NJ" }, { c: "Woodbridge", s: "NJ" },
  { c: "San Angelo", s: "TX" }, { c: "Kenosha", s: "WI" }, { c: "Vacaville", s: "CA" },
  { c: "Bend", s: "OR" }, { c: "Asheville", s: "NC" }, { c: "Spartanburg", s: "SC" },
  { c: "Greenville", s: "SC" }, { c: "Myrtle Beach", s: "SC" }, { c: "Sarasota", s: "FL" },
  { c: "Naples", s: "FL" }, { c: "Boca Raton", s: "FL" }, { c: "Delray Beach", s: "FL" },
  { c: "Jupiter", s: "FL" }, { c: "Kissimmee", s: "FL" }, { c: "Ocala", s: "FL" },
  { c: "Fort Myers", s: "FL" }, { c: "Bradenton", s: "FL" }, { c: "Daytona Beach", s: "FL" },
  { c: "Chapel Hill", s: "NC" }, { c: "Boone", s: "NC" }, { c: "Bozeman", s: "MT" },
  { c: "Missoula", s: "MT" }, { c: "Coeur d'Alene", s: "ID" }, { c: "Idaho Falls", s: "ID" },
  { c: "Bentonville", s: "AR" }, { c: "Fayetteville", s: "AR" }, { c: "Rogers", s: "AR" },
  { c: "St. George", s: "UT" }, { c: "Ogden", s: "UT" }, { c: "Lehi", s: "UT" },
  { c: "Flagstaff", s: "AZ" }, { c: "Prescott", s: "AZ" }, { c: "Yuma", s: "AZ" },
  { c: "Santa Fe", s: "NM" }, { c: "Cheyenne", s: "WY" }, { c: "Casper", s: "WY" },
  { c: "Jackson", s: "WY" }, { c: "Rapid City", s: "SD" }, { c: "Bismarck", s: "ND" },
  { c: "Duluth", s: "MN" }, { c: "Bloomington", s: "MN" }, { c: "Iowa City", s: "IA" },
  { c: "Springfield", s: "IL" }, { c: "Peoria", s: "IL" }, { c: "Champaign", s: "IL" },
  { c: "Bloomington", s: "IN" }, { c: "Carmel", s: "IN" }, { c: "Fishers", s: "IN" },
  { c: "Kalamazoo", s: "MI" }, { c: "Flint", s: "MI" }, { c: "Youngstown", s: "OH" },
  { c: "Canton", s: "OH" }, { c: "Erie", s: "PA" }, { c: "Scranton", s: "PA" },
  { c: "Harrisburg", s: "PA" }, { c: "Lancaster", s: "PA" }, { c: "Bethlehem", s: "PA" },
  { c: "Reading", s: "PA" }, { c: "Trenton", s: "NJ" }, { c: "Camden", s: "NJ" },
  { c: "Hoboken", s: "NJ" }, { c: "Albany", s: "NY" }, { c: "White Plains", s: "NY" },
  { c: "New Rochelle", s: "NY" }, { c: "Ithaca", s: "NY" }, { c: "Burlington", s: "VT" },
  { c: "Portland", s: "ME" }, { c: "Portsmouth", s: "NH" }, { c: "Nashua", s: "NH" },
  { c: "Quincy", s: "MA" }, { c: "Brockton", s: "MA" }, { c: "New Bedford", s: "MA" },
  { c: "Cranston", s: "RI" }, { c: "Warwick", s: "RI" }, { c: "Dover", s: "DE" },
  { c: "Wilmington", s: "DE" }, { c: "Annapolis", s: "MD" }, { c: "Frederick", s: "MD" },
  { c: "Silver Spring", s: "MD" }, { c: "Bethesda", s: "MD" }, { c: "Rockville", s: "MD" },
  { c: "Arlington", s: "VA" }, { c: "Roanoke", s: "VA" }, { c: "Charlottesville", s: "VA" },
  { c: "Lynchburg", s: "VA" }, { c: "Charleston", s: "WV" }, { c: "Morgantown", s: "WV" },
  { c: "Lexington", s: "SC" }, { c: "Rock Hill", s: "SC" }, { c: "Concord", s: "NC" },
  { c: "Gastonia", s: "NC" }, { c: "Johnson City", s: "TN" }, { c: "Franklin", s: "TN" },
  { c: "Hendersonville", s: "TN" }, { c: "Bowling Green", s: "KY" }, { c: "Owensboro", s: "KY" },
  { c: "Huntsville", s: "TX" }, { c: "Galveston", s: "TX" }, { c: "New Braunfels", s: "TX" },
  { c: "Georgetown", s: "TX" }, { c: "Temple", s: "TX" }, { c: "Conroe", s: "TX" },
  { c: "The Woodlands", s: "TX" }, { c: "Katy", s: "TX" }, { c: "Prosper", s: "TX" },
  { c: "Lake Charles", s: "LA" }, { c: "Metairie", s: "LA" }, { c: "Gulfport", s: "MS" },
  { c: "Biloxi", s: "MS" }, { c: "Hattiesburg", s: "MS" }, { c: "Dothan", s: "AL" },
  { c: "Auburn", s: "AL" }, { c: "Columbus", s: "MS" }, { c: "Pensacola", s: "FL" },
  { c: "Panama City", s: "FL" }, { c: "Destin", s: "FL" }, { c: "Alpharetta", s: "GA" },
  { c: "Marietta", s: "GA" }, { c: "Roswell", s: "GA" }, { c: "Decatur", s: "GA" },
  { c: "Valdosta", s: "GA" }, { c: "Albany", s: "GA" }, { c: "Anchorage", s: "AK" },
  { c: "Fairbanks", s: "AK" }, { c: "Juneau", s: "AK" }, { c: "Hilo", s: "HI" },
  { c: "Kailua", s: "HI" }, { c: "Bellingham", s: "WA" }, { c: "Olympia", s: "WA" },
  { c: "Yakima", s: "WA" }, { c: "Spokane Valley", s: "WA" }, { c: "Medford", s: "OR" },
  { c: "Corvallis", s: "OR" }, { c: "Beaverton", s: "OR" }, { c: "Napa", s: "CA" },
  { c: "Santa Barbara", s: "CA" }, { c: "San Luis Obispo", s: "CA" }, { c: "Monterey", s: "CA" },
  { c: "Palo Alto", s: "CA" }, { c: "Mountain View", s: "CA" }, { c: "San Jose", s: "CA" },
  { c: "Walnut Creek", s: "CA" }, { c: "Sausalito", s: "CA" }, { c: "Truckee", s: "CA" },
  { c: "Palm Springs", s: "CA" }, { c: "Redlands", s: "CA" }, { c: "Chico", s: "CA" },
  { c: "Redding", s: "CA" }, { c: "Eureka", s: "CA" }, { c: "Grand Junction", s: "CO" },
  { c: "Durango", s: "CO" }, { c: "Aspen", s: "CO" }, { c: "Vail", s: "CO" },
  { c: "Breckenridge", s: "CO" }, { c: "Loveland", s: "CO" }, { c: "Longmont", s: "CO" },
  { c: "Castle Rock", s: "CO" }, { c: "Park City", s: "UT" }, { c: "Moab", s: "UT" },
  { c: "Taos", s: "NM" }, { c: "Sedona", s: "AZ" }, { c: "Lake Havasu City", s: "AZ" },
  { c: "Queen Creek", s: "AZ" }, { c: "Buckeye", s: "AZ" }, { c: "Goodyear", s: "AZ" },
  { c: "Casa Grande", s: "AZ" }, { c: "Maricopa", s: "AZ" }, { c: "Apache Junction", s: "AZ" },
];
